### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by yadaiio**
This pull request fixes a few typos with the help of https://github.com/szepeviktor/typos-on-you.

Builds on top of #10 and https://github.com/clue/reactphp-redis/pull/146.

### CODE REVIEW

**Comment by SimonFrings** [comment]
Thanks for your contribution :+1: 

Pull request itself looks good. The test matrix is currently not running through because of an outdated CI workflow, so we need to make a few adjustments before we can merge this. The changes will be similar to the work done in https://github.com/reactphp/socket/pull/299, https://github.com/reactphp/socket/pull/300 and https://github.com/reactphp/socket/pull/310.

Is this something you can look into?

**Comment by SimonFrings** [comment]
@yadaiio I just created a pull request to update the test suite so that your checks should be green after #33 is merged.

**Comment by yadaiio** [comment]
Thanks to @SimonFrings, I was able to rebase my branch after implementing the new feature described in #33. Fortunately, there were no conflicts, and all tests passed successfully.

This PR is now ready to be reviewed by @clue and @SimonFrings. 🎉

**Comment by yadaiio** [comment]
> Thanks for your contribution 👍
> 
> Pull request itself looks good. The test matrix is currently not running through because of an outdated CI workflow, so we need to make a few adjustments before we can merge this. The changes will be similar to the work done in [reactphp/socket#299](https://github.com/reactphp/socket/pull/299), [reactphp/socket#300](https://github.com/reactphp/socket/pull/300) and [reactphp/socket#310](https://github.com/reactphp/socket/pull/310).
> 
> Is this something you can look into?

Really thankful for our workshop. I feel confident that I will be able to work on this independently in the future. 🥳

**Review by SimonFrings — APPROVED** [review]
@yadaiio Thanks for rebasing, these changes look good to me :+1:

**Review by clue — APPROVED** [review]
@yadaiio Thanks for looking into this, changes LGTM! :shipit:

**Pull request merged**
